apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cinetribe-mcp-tmdb
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Cloud Run resource allocation
        run.googleapis.com/cpu: "1"
        run.googleapis.com/memory: "512Mi"
        run.googleapis.com/max-instances: "10"
        run.googleapis.com/min-instances: "0"
        # Cloud Run networking
        run.googleapis.com/vpc-access-connector: ""
        run.googleapis.com/vpc-access-egress: private-ranges-only
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/cinetribe-mcp-tmdb:latest
        name: cinetribe-mcp-tmdb
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: TMDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: tmdb-api-key
              key: api-key
        - name: NODE_ENV
          value: "production"
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true
