# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Optimized for Google Cloud Run deployment
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json and package-lock.json are copied
COPY package*.json ./

# Install dependencies (ignoring prepare scripts to avoid auto-build if necessary)
RUN npm install --ignore-scripts

# Build the project explicitly
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

# Verify the build output
RUN ls -la dist/ && echo "Build completed successfully"

# Bundle app source
# Expose a volume if necessary, but here we assume a command line tool

# Cloud Run expects the app to listen on the PORT environment variable
ENV PORT=8080
ENV NODE_ENV=production
EXPOSE $PORT

# Default command - Cloud Run will provide the PORT environment variable
CMD ["npm", "start"]
